language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install --quiet -g gulp bower
- bower install || bower install || bower install || bower install || bower install
script: gulp ci
cache:
  directories:
  - vendor
  - node_modules
notifications:
  hipchat:
    rooms:
      secure: QD5mL+SG+V3gSV8CKPK8oMh+ga9oygOJwxnIev3ik5dA7G5eH81penO9wSMeypyUp66RbVaJrp5tKTmBWFdI+HTIT7cNYGeujUxOn+GJ51c02lLjEHmNKja/VU+CzSOd42nhPPNGib3WRhFYKiGolBnePeoe83jF76W7zkFcslY=
    template:
      - '<strong>%{repository_name}#%{commit} on %{branch} by %{author}</strong> (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
